version: "3.6"

services:
  # Postgres
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@postgres:5432/recognition-app
      POSTGRES_DB: recognition-app
      POSTGRES_HOST: postgres
      CLARIFAI_API_KEY: 0fd2c5196ec746c696d52ed7524229f3
    ports:
      - "5432:5432"
  # NodeJS
  recognition-app-api:
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/recognition-app-api
    command: npm start
    working_dir: /usr/src/recognition-app-api
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/recognition-app
